# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Oct 16 20:13:02 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.basicGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.basicGroupBox.setGeometry(QtCore.QRect(14, 12, 411, 350))
        self.basicGroupBox.setFlat(False)
        self.basicGroupBox.setObjectName("basicGroupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.basicGroupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 390, 316))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.fontLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fontLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.fontLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fontLabel.setObjectName("fontLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fontLabel)
        self.fontbutton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.fontbutton.setObjectName("fontbutton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fontbutton)
        self.characterSetLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.characterSetLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.characterSetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.characterSetLabel.setObjectName("characterSetLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.characterSetLabel)
        self.characterSetBox = QtWidgets.QPlainTextEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.characterSetBox.sizePolicy().hasHeightForWidth())
        self.characterSetBox.setSizePolicy(sizePolicy)
        self.characterSetBox.setMaximumSize(QtCore.QSize(16777215, 192))
        self.characterSetBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.characterSetBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.characterSetBox.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.characterSetBox.setBackgroundVisible(False)
        self.characterSetBox.setObjectName("characterSetBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.characterSetBox)
        self.fillColorLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fillColorLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.fillColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fillColorLabel.setObjectName("fillColorLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fillColorLabel)
        self.fillColor = QtWidgets.QFrame(self.formLayoutWidget_2)
        self.fillColor.setMinimumSize(QtCore.QSize(230, 32))
        self.fillColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fillColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fillColor.setObjectName("fillColor")
        self.fillColorButton = QtWidgets.QPushButton(self.fillColor)
        self.fillColorButton.setGeometry(QtCore.QRect(0, 1, 81, 32))
        self.fillColorButton.setObjectName("fillColorButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fillColor)
        self.fillAngleLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fillAngleLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.fillAngleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fillAngleLabel.setObjectName("fillAngleLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fillAngleLabel)
        self.fillAngleBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.fillAngleBox.setObjectName("fillAngleBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fillAngleBox)
        self.strokeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.strokeGroupBox.setGeometry(QtCore.QRect(14, 560, 411, 110))
        self.strokeGroupBox.setCheckable(True)
        self.strokeGroupBox.setChecked(False)
        self.strokeGroupBox.setObjectName("strokeGroupBox")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.strokeGroupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 364, 74))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.strokeColorLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.strokeColorLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.strokeColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.strokeColorLabel.setObjectName("strokeColorLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.strokeColorLabel)
        self.strokeColor = QtWidgets.QFrame(self.formLayoutWidget_3)
        self.strokeColor.setMinimumSize(QtCore.QSize(230, 32))
        self.strokeColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.strokeColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.strokeColor.setObjectName("strokeColor")
        self.strokeColorButton = QtWidgets.QPushButton(self.strokeColor)
        self.strokeColorButton.setGeometry(QtCore.QRect(0, 1, 82, 32))
        self.strokeColorButton.setObjectName("strokeColorButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.strokeColor)
        self.strokeWidthLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.strokeWidthLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.strokeWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.strokeWidthLabel.setObjectName("strokeWidthLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.strokeWidthLabel)
        self.strokeWidthBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.strokeWidthBox.setObjectName("strokeWidthBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.strokeWidthBox)
        self.dropShadowGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.dropShadowGroupBox.setGeometry(QtCore.QRect(14, 370, 411, 180))
        self.dropShadowGroupBox.setCheckable(True)
        self.dropShadowGroupBox.setChecked(False)
        self.dropShadowGroupBox.setObjectName("dropShadowGroupBox")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.dropShadowGroupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 360, 142))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.shadowColorLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.shadowColorLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.shadowColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shadowColorLabel.setObjectName("shadowColorLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.shadowColorLabel)
        self.shadowColor = QtWidgets.QFrame(self.formLayoutWidget_4)
        self.shadowColor.setMinimumSize(QtCore.QSize(230, 32))
        self.shadowColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shadowColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shadowColor.setObjectName("shadowColor")
        self.shadowColorButton = QtWidgets.QPushButton(self.shadowColor)
        self.shadowColorButton.setGeometry(QtCore.QRect(0, 1, 81, 32))
        self.shadowColorButton.setObjectName("shadowColorButton")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shadowColor)
        self.shadowAngleLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.shadowAngleLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.shadowAngleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shadowAngleLabel.setObjectName("shadowAngleLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.shadowAngleLabel)
        self.shadowAngleBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.shadowAngleBox.setMinimum(-360.0)
        self.shadowAngleBox.setMaximum(360.0)
        self.shadowAngleBox.setObjectName("shadowAngleBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shadowAngleBox)
        self.shadowSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.shadowSizeLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.shadowSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shadowSizeLabel.setObjectName("shadowSizeLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.shadowSizeLabel)
        self.shadowSizeBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.shadowSizeBox.setObjectName("shadowSizeBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.shadowSizeBox)
        self.shadowDistanceLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.shadowDistanceLabel.setMinimumSize(QtCore.QSize(115, 0))
        self.shadowDistanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shadowDistanceLabel.setObjectName("shadowDistanceLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.shadowDistanceLabel)
        self.shadowDistanceBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.shadowDistanceBox.setObjectName("shadowDistanceBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shadowDistanceBox)
        self.widget = QPaintArea(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(440, 30, 351, 501))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(440, 550, 160, 134))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exportSeperateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exportSeperateButton.setObjectName("exportSeperateButton")
        self.verticalLayout.addWidget(self.exportSeperateButton)
        self.exportGroupButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exportGroupButton.setObjectName("exportGroupButton")
        self.verticalLayout.addWidget(self.exportGroupButton)
        self.saveSettingsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.verticalLayout.addWidget(self.saveSettingsButton)
        self.loadSettingsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadSettingsButton.setObjectName("loadSettingsButton")
        self.verticalLayout.addWidget(self.loadSettingsButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.basicGroupBox.setTitle(_translate("MainWindow", "Font Information"))
        self.fontLabel.setText(_translate("MainWindow", "Font"))
        self.fontbutton.setText(_translate("MainWindow", "Pick Font"))
        self.characterSetLabel.setText(_translate("MainWindow", "Character Set:"))
        self.characterSetBox.setPlainText(_translate("MainWindow", "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890[]\'#;,./\\`¬!\"£$%^&*()_+{}:@~?><|"))
        self.fillColorLabel.setText(_translate("MainWindow", "Fill Color"))
        self.fillColorButton.setText(_translate("MainWindow", "Select"))
        self.fillAngleLabel.setText(_translate("MainWindow", "Fill Angle"))
        self.strokeGroupBox.setTitle(_translate("MainWindow", "Stroke"))
        self.strokeColorLabel.setText(_translate("MainWindow", "Stroke Color"))
        self.strokeColorButton.setText(_translate("MainWindow", "Select"))
        self.strokeWidthLabel.setText(_translate("MainWindow", "Stroke Width"))
        self.dropShadowGroupBox.setTitle(_translate("MainWindow", "Drop Shadow"))
        self.shadowColorLabel.setText(_translate("MainWindow", "Shadow Color"))
        self.shadowColorButton.setText(_translate("MainWindow", "Select"))
        self.shadowAngleLabel.setText(_translate("MainWindow", "Shadow Angle"))
        self.shadowSizeLabel.setText(_translate("MainWindow", "Shadow Size"))
        self.shadowDistanceLabel.setText(_translate("MainWindow", "Shadow Distance"))
        self.exportSeperateButton.setText(_translate("MainWindow", "Export Individual"))
        self.exportGroupButton.setText(_translate("MainWindow", "Export Group"))
        self.saveSettingsButton.setText(_translate("MainWindow", "Save Settings"))
        self.loadSettingsButton.setText(_translate("MainWindow", "Load Settings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

from qpaintarea import QPaintArea
